# permissions for end users to edit quickstarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: quick-start
    app.kubernetes.io/managed-by: kustomize
  name: quickstart-editor-role
rules:
- apiGroups:
  - webapp.github.com
  resources:
  - quickstarts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.github.com
  resources:
  - quickstarts/status
  verbs:
  - get
