apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa
  minReplicas: 1
  maxReplicas: 10
  behavior:
    # We want to add a maximum of 1 pod every 60 seconds when scaling up
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    # We want to remove a maximum of 10% of pods every 60 seconds when scaling down
    scaleDown:
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
  metrics:
    # Here we define the average number of cpu and memory we want to use
    # We want to keep the average cpu usage to 80% and keep the average resource usage to 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
