apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/api

commonLabels:
  app: log-server

patchesStrategicMerge:
  - deployment.yaml

replicas:
  - name: log-server
    count: 3
