apiVersion: v1
kind: Service
metadata:
  name: query-logger
  namespace: query-logger
spec:
  type: LoadBalancer
  selector:
    app: query-logger
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
