# permissions for end users to edit busyboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: busybox
    app.kubernetes.io/managed-by: kustomize
  name: busybox-editor-role
rules:
- apiGroups:
  - intro.github.com
  resources:
  - busyboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intro.github.com
  resources:
  - busyboxes/status
  verbs:
  - get
