apiVersion: intro.github.com/v1alpha
kind: Busybox
metadata:
  labels:
    app.kubernetes.io/name: busybox
    app.kubernetes.io/managed-by: kustomize
  name: busybox-sample
spec:
  size: 1
  # TODO(user): Add fields here
