apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-server
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
