apiVersion: v1
kind: Service
metadata:
  name: log-server
  namespace: devops
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 8000
  selector:
    app: log-server
  type: LoadBalancer
